name: series_distance
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - scipy
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - tqdm
  - ipykernel
  - ipython
  - gsd
  - mdanalysis
  - netcdf4
  - h5py
  - openpyxl
  - pip
  - pip:
      - pyedr
